### ISSUE TITLE
没启动起来

### ISSUE THREAD

**Issue by LonelyFellas** [luxi-record/react-sourceCodeDebug#1]
我照你流程clone下来，然后npm i ，当npm run dev的时候没有启动起来。
![WX20230816-154208@2x](https://github.com/luxi-record/react-sourceCodeDebug/assets/38754760/c70c8684-c062-457e-bf83-da8f34a5f85b)
应该是什么原因

**Comment by luxi-record** [comment]
大概是node的问题，你可以尝试重新安装node 18.12.0版本，或者卸载node_modules重新安装。

**Comment by LonelyFellas** [comment]
我现在启动起来了，我一开始用了yarn安装依赖，但是呢后面我yarn run dev的时候，没有成功，后面我在重新用npm i 的时候，应该重新吧原来node_modules删掉，导致我一直报这个错误。

**Comment by luxi-record** [comment]
最好别yarn npm pnpm 混用

**Comment by LonelyFellas** [comment]
行的

**Comment by LonelyFellas** [comment]
单react18.2.0版本中，有几个文件名被移动和修改，所以你在掘金那片文章没跑起来，你可以看一下

**Comment by LonelyFellas** [comment]
说错了是最近的18.2.0吧。我从原仓库clone出来的

**Comment by luxi-record** [comment]
18.2都是一些fix的更新，所以没有升级react的版本，该仓库主要帮助我们熟悉react18的事件，diff，调度任务流程
